dist: xenial
services:
- postgresql
branches:
  only:
  - master
  - develop
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install codacy-coverage
script:
- npm -g install phantomjs
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py makemigrations
- python ./manage.py migrate
- python ./manage.py loaddata decideDB.json
- python manage.py runserver &
- python ./manage.py test --keepdb
- coverage run --branch --source=. ./manage.py test --keepdb
- coverage xml
- python-codacy-coverage -r coverage.xml
- rm local_settings.py
deploy:
  provider: heroku
  app: decidemoltres-votacion
  strategy: git
  api_key:
    secure: 6dc2c94a-ed44-4077-8c00-ca13c2236989
